// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_bM0D2SERLbSAFbr3J7-Pj1ewvM6CC7o',
    appId: '1:361557352430:web:c5aa46095f5d1af72eb8ff',
    messagingSenderId: '361557352430',
    projectId: 'food-rescue-b344d',
    authDomain: 'food-rescue-b344d.firebaseapp.com',
    storageBucket: 'food-rescue-b344d.appspot.com',
    measurementId: 'G-MBV31SFEWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGlkJWzlUbVD2KiM3K2K-ySrbofejsyOs',
    appId: '1:361557352430:android:8456e6e526b1b1832eb8ff',
    messagingSenderId: '361557352430',
    projectId: 'food-rescue-b344d',
    storageBucket: 'food-rescue-b344d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEK0Db7KT5LqeiZcHN0SVO_XyHC86uRaI',
    appId: '1:361557352430:ios:ec3e2b28d7ddac4e2eb8ff',
    messagingSenderId: '361557352430',
    projectId: 'food-rescue-b344d',
    storageBucket: 'food-rescue-b344d.appspot.com',
    iosClientId: '361557352430-jpiimsc2mhi2fbe5cjip8lgc2q27kjac.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodRescue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEK0Db7KT5LqeiZcHN0SVO_XyHC86uRaI',
    appId: '1:361557352430:ios:ec3e2b28d7ddac4e2eb8ff',
    messagingSenderId: '361557352430',
    projectId: 'food-rescue-b344d',
    storageBucket: 'food-rescue-b344d.appspot.com',
    iosClientId: '361557352430-jpiimsc2mhi2fbe5cjip8lgc2q27kjac.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodRescue',
  );
}
